[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
