[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/public/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/assets/*/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/public/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/assets/*/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/public/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/assets/*/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/public/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/assets/*/*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "/public/*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"